name: Deploy fatura personalizada micro serviÃ§o de integraÃ§Ã£o com openIa

on:
  pull_request:
    branches:
      - main # Branch de destino para gerenciar releases
    types:
      - closed

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # PermissÃ£o para o workflow criar tags

    steps:
      - uses: actions/checkout@v3

      - name: Config git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Instalar dependÃªncias
        run: npm install

      - name: Criar release com release-it
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Obter tag da release
        id: extract_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Construir e publicar imagem
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./infra/docker/Dockerfile.prod --build-arg SERVICE_VERSION=${{ env.TAG }} --tag ghcr.io/oondemand/api-integracao-gpt:${{ env.TAG }} .
          docker push ghcr.io/oondemand/api-integracao-gpt:${{ env.TAG }}

      - name: Criar kubeconfig
        run: |
          mkdir -p "${HOME}/.kube"
          curl -s -H "Authorization: Bearer ${{secrets.DO_ACCESS_TOKEN}}" "${{secrets.DO_CLUSTER_AUTHENTICATION_URL}}" > "$HOME/.kube/config"

      - name: Usar contexto do cluster
        run: |
          kubectl config use-context ${{ secrets.CLUSTER }}

      - name: ðŸš€ Substituir variÃ¡veis no deployment.yml e aplicar no cluster
        run: |
          envsubst < infra/kubernetes/deployment.yaml | kubectl apply -f -

        env:
          IMAGE_TAG: ${{ env.TAG }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          OPEN_IA_SECRET_KEY: ${{ secrets.OPEN_IA_SECRET_KEY }}
